###########################################
##  Author: Fiorenzo Tittaferrante       ##
##  Creation: 2022 May 09                ##
##  Last update: 2022 May 11             ##
##  File: docker-compose.yml             ##
##  Purpose: settings up kong container  ##
###########################################

version: "3.2"

services:

  #######################################
  ######   Kong: The API Gateway   ######
  #######################################

  kong-gateway:
    image: kong/kong-gateway:2.8.1.0-alpine
    container_name: kong-gateway
    
    environment:
      # Database Environment 
      KONG_DATABASE: postgres
      KONG_PG_USER: fiorenzo@postgresqlkong
      KONG_PG_HOST: postgresqlkong.postgres.database.azure.com
      KONG_PG_PASSWORD: aesys-tech2022
      KONG_PG_DATABASE: fattdb

      # Kong listen addresses
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://checkemail.westeurope.cloudapp.azure.com:8002
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PORTAL_CORS_ORIGINS: http://checkemail.westeurope.cloudapp.azure.com:8002

      # Log output
      KONG_PROXY_ACCESS_LOG: /usr/local/kong/logs/portal_api_access.log
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /usr/local/kong/logs/portal_api_error.log
      KONG_ADMIN_ERROR_LOG: /usr/local/kong/logs/admin_gui_error.log
      KONG_LOG_LEVEL: debug

      # Kong plugins
      KONG_PLUGINS: bundled,checkemail
 
    networks:
      - kong-net
      
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8443:8443"
      - "8003:8003"
      - "8004:8004"
      - "8444:8444"
      - "8445:8445"
   

networks:
  kong-net: {}
